on: [push, pull_request, workflow_dispatch]

jobs:
  conan_stable_linux:
    runs-on: ubuntu-20.04
    env:
      CONAN_LOGIN_USERNAME_EXTENSIONS_PROD: ${{ secrets.CONAN_USER }}
      CONAN_PASSWORD_EXTENSIONS_PROD: ${{ secrets.CONAN_PASSWORD }}
      CONAN_LOGIN_USERNAME_EXTENSIONS_STG: ${{ secrets.CONAN_USER }}
      CONAN_PASSWORD_EXTENSIONS_STG: ${{ secrets.CONAN_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install pytest conan
    - name: Conan latest - Python 3.6
      run: |
        pytest -v tests
