on: [pull_request, workflow_dispatch]

jobs:
  conan_stable_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install pytest conan
    - name: Conan latest - Python 3.6
      run: |
        pytest -v tests
